name = "didgit-permission-blob"
main = "src/index.ts"
compatibility_date = "2024-11-01"
node_compat = true

[vars]
ALLOWED_ORIGIN = "https://didgit.dev"

# Secrets:
# wrangler secret put VERIFIER_PRIVKEY
# wrangler secret put API_KEY
